export const themesStyleConfig = [
  {
  themesName:"professional-corporate-minimalist",
  base: "mx-auto p-8 bg-white text-slate-800 shadow-sm w-full max-w-[210mm] box-border print:p-0",
  header: "border-b-2 border-slate-900 pb-4 mb-6",
  infoHeader: "flex flex-col md:flex-row justify-between items-start gap-4",
  name: "text-4xl font-bold tracking-tight text-slate-900 uppercase leading-none",
  jobTitle: "text-lg font-medium tracking-widest uppercase text-slate-500 mt-1",
  sectionTitle: "text-sm font-bold uppercase tracking-[0.2em] text-slate-900 border-l-4 border-slate-900 pl-3 mb-4",
  contact: "flex flex-col items-start md:items-end text-slate-600 space-y-0.5 w-full md:w-auto ",
  additionalInfo: "flex flex-wrap gap-x-4 gap-y-1 mt-4 pt-3 border-t border-slate-100 font-bold uppercase tracking-wider text-slate-400",
  main: "space-y-6",
  sectionItem: "mb-4 last:mb-0 break-inside-avoid",
  sectionHeader: "flex flex-col sm:flex-row justify-between items-start sm:items-baseline mb-1 gap-1",
  sectionHeaderTitle: "font-bold uppercase text-slate-800",
  sectionHeaderInfo: "text-slate-500 sm:text-right uppercase",
  summary: "text-justify max-w-[700px] break-all break-inside-avoid",
  summaryContent: "mb-6 max-w-full",
  sectionDesc: "text-slate-600 mt-2 max-w-[700px] break-all prose-p:m-0",
  testSectionItem:"mb-4 last:mb-0 break-inside-avoid",
  testSectionHeader:"flex flex-col sm:flex-row justify-between items-start sm:items-baseline mb-1 gap-1",
  testSectionInfo:"text-slate-500 sm:text-right uppercase"
  },
  {
  themesName:"twoColumn-professional",
  base: "w-full max-w-[210mm] mx-auto bg-white shadow-2xl flex flex-col md:flex-row print:shadow-none print:flex-row",
  header: "w-full md:w-[42%] bg-slate-900 text-slate-200 p-8 md:p-10 flex flex-col gap-5 break-words print:w-[42%]", 
  infoHeader: "flex flex-col gap-2",
  jobTitle: "text-xs font-bold tracking-[0.25em] text-indigo-400 uppercase",
  name: "text-3xl md:text-4xl font-black uppercase tracking-tighter leading-none break-words",
  contact: "flex flex-col gap-2",
  additionalInfo: "grid grid-cols-1 gap-2 mt-4 pt-5 border-t border-slate-700/50 uppercase",
  main: "w-full md:w-[58%] p-8 md:p-12 bg-white flex flex-col gap-10 print:w-[58%]",
  sectionTitle: "text-lg font-extrabold border-b-2 border-slate-900 mb-6 pb-2 text-slate-900 uppercase tracking-tighter",
  sectionItem: "mb-8 last:mb-0 break-inside-avoid",
  sectionHeader: "mb-2",
  sectionHeaderTitle: "font-bold text-slate-800 uppercase",
  sectionHeaderInfo: "font-semibold text-indigo-600 mb-2 flex flex-wrap justify-between gap-2",
  sectionDesc: "text-slate-600 mt-2 max-w-[700px] break-all prose-p:m-0",
  summary: "bg-slate-50 p-5 border-l-4 border-indigo-500 rounded-r-sm",
  summaryContent: "text-slate-700 text-justify max-w-[700px] break-all break-inside-avoid",
  testSectionItem:"mb-8 last:mb-0 break-inside-avoid",
  testSectionHeader:"mb-2",
  testSectionInfo:"font-semibold text-indigo-600 mb-2 flex flex-wrap justify-between gap-2"
  },
  {
  themesName:"creative",
  base: "w-full max-w-[210mm] mx-auto my-10 p-12 bg-slate-950 relative text-slate-200 shadow-2xl before:content-[''] before:absolute before:top-6 before:right-6 before:w-12 before:h-12 before:border-t-4 before:border-r-4 before:border-orange-500 after:content-[''] after:absolute after:bottom-6 after:left-6 after:w-12 after:h-12 after:border-b-4 after:border-l-4 after:border-orange-500",
  header: "relative mb-12 border-b border-slate-800 pb-8",
  infoHeader: "flex flex-col gap-1",
  jobTitle: "text-sm font-black tracking-[0.5em] uppercase text-orange-500",
  name: "text-6xl font-black tracking-tighter text-white uppercase",
  contact: "mt-6 flex flex-wrap gap-x-6 gap-y-2 font-extrabold text-slate-400 uppercase tracking-widest",
  additionalInfo: "flex flex-wrap items-center gap-x-4 mt-6 text-[10px] font-bold uppercase tracking-widest text-orange-500/80",
  main: "space-y-12",
  sectionTitle: "flex items-center p-1 text-2xl border-b-3 pb-2 border-orange-500 font-black uppercase tracking-tighter text-white mb-8 before:content-[''] before:w-3 before:h-3 before:bg-orange-500 before:mr-4 before:rounded-full outline-none",
  summary: "text-slate-400 italic border-l-2 border-orange-500/30 pl-6 max-w-[700px] break-all break-inside-avoid",
  summaryContent: "mb-4",
  sectionItem: "relative pl-7 pb-7 border-l border-slate-800 break-inside-avoid",
  sectionHeader: "flex flex-col gap-3 mb-3 relative before:content-[''] before:absolute before:-left-[36.5px] before:top-1.5 before:w-4 before:h-4 before:bg-slate-400 before:border-2 before:border-orange-500 before:rounded-full",
  sectionHeaderTitle: "text-lg font-bold text-white tracking-tight",
  sectionHeaderInfo: "font-black text-orange-500 uppercase tracking-wider",
  sectionDesc: "text-slate-400 max-w-[700px] break-all break-inside-avoid",
  testSectionItem:"mb-4 last:mb-0 break-inside-avoid",
  testSectionHeader:"mb-2",
  testSectionInfo:"font-semibold uppercase text-orange-600 mb-2 flex flex-wrap justify-between gap-3"
}]